import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";
import Header from "@/app/component/layout/header";
import Footer from "@/app/component/layout/footer";
import { Toaster } from "@/components/ui/toaster";

const fontSans = Quicksand({
  subsets: ["latin"],
  weight:['500','600','700']
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "E-commerce Web",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="vi">
      <body
        className={fontSans.className}
      >
        <div className= {"min-h-screen flex flex-col justify-between"} >
        <Header/>
        <main className="mt-24 p-10 "> 

        {children}

        </main>
        <Footer/>
          
        </div>
        <Toaster></Toaster>
      </body>
    </html>
  );
}
